#!/usr/bin/env node

"use strict";

const connect = require("connect");
const http = require("http");
const fs = require("fs");
const MemoryFS = require("memory-fs");
const path = require("path");
const webpack = require("webpack");

const app = connect();
const memoryFs = new MemoryFS();

app.use(function(req, res) {
    const requirePath = path.join(
        path.relative(__dirname, process.cwd()),
        req.url
    );

    // chdir here so relative requires work
    process.chdir(__dirname);

    if (req.url === "/") {
        res.end(`<pre>
Welcome!

Go ahead and put some react components in here.

$ echo 'import React from "react"; export default () => &lt;div&gt;Hello, world\!&lt;/div&gt;' > HelloWorld.js

Then go here: <a href="/HelloWorld.js">http://localhost:3000/HelloWorld.js</a>

Thanks!
        </pre>`);
    }

    if (!fs.existsSync(requirePath)) {
        return res.end(`No module found at ${req.url}`);
    }

    const compiler = webpack({
        entry: "./entry.js",
        output: {
            path: "/",
            filename: "bundle.js",
        },
        module: {
            loaders: [
                {
                    test: /\.jsx?$/,
                    loader: "babel-loader",
                    exclude: /node_modules/,
                    query: {
                        presets: ["es2015", "react"],
                    },
                },
            ],
        },
        plugins: [
            new webpack.DefinePlugin({
                REQUIRE_PATH: JSON.stringify(requirePath),
            }),
        ],
    });
    compiler.outputFileSystem = memoryFs;

    compiler.run(function(err, stats) {
        if (err) {
            return res.end(err.stack);
        }

        const fileContent = memoryFs.readFileSync("/bundle.js");

        res.end(`
            <div id="main"></div>
            <script>${fileContent}</script>
        `);
    });
});

const port = process.env.PORT || 3000;
console.log(`Server listening on port ${port}`);
http.createServer(app).listen(port);
